### ISSUE TITLE
Heatmap url not accessible

### ISSUE THREAD

**Issue by belambic** [crazy-max/docker-matomo#117]
#### Steps to reproduce this issue

1. Go to the Matomo system check
2. Go to "Heatmap & Session Recording Tracking"
3. See the error:  The URL 'https://.../data-plugins/HeatmapSessionRecording/configs.php?idsite=1&trackerid=5lX6EM&url=http%3A%2F%2Ftest.test%2F' seems to be not accessible from the Internet or Intranet. As a result, tracking Heatmaps and Session Recordings may not work. You may need to change your webserver configuration to allow access to this file via the Internet or Intranet. 
4. Visiting the URL in the browser gives "Forbidden"

#### Expected behaviour

The required URL should be accessible

#### Actual behaviour

The above error

### Configuration

AWS Kubernetes cluster, matomo installed with Helm.

**Comment by mirabuck** [comment]
Giving this a gentle bump.

**Comment by biki** [comment]
This is still an issue.

**Comment by theexiile1305** [comment]
My installation is also affected. The URL `https://<base-url>/data-plugins/HeatmapSessionRecording/configs.php?idsite=1&trackerid=5lX6EM&url=http://test.test/` is not accessible.

**Comment by theexiile1305** [comment]
@crazy-max so that issue can now also be closed.
