### ISSUE TITLE
Create release for 4.13.3

### ISSUE THREAD

**Issue by benr77** [crazy-max/docker-matomo#123]
Hello. Thanks for a great repo. Any chance you could create a build for the latest 4.13.3 release? Thanks!

**Comment by rafaelmaeuer** [comment]
Instead of polluting this repo with PR-Updates why not invest some time to use something like matomo:latest?
This would reduce the need for @crazy-max to regularly approve PRs and having always updated versions?
Any thoughts on this?

**Comment by benr77** [comment]
Great idea. I guess it's also possible to trigger a build automatically when Matomo releases a new version? Github Actions?

@crazy-max Thanks for tagging a new release for 4.13.3
