### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by davidrot** [crazy-max/docker-matomo#13]
Hello,

thank you for your very complete setup. While the installation in step 3 the database is not reachable. 
I havn't changed the docker-compose.yml, should I?

Here is the exact error message 

`Error while trying to connect to the database server: SQLSTATE[HY000] [2002] Connection refused `

I wasnt able to connect to the database directly with the mysql command.

**Comment by crazy-max** [comment]
Hi @davidrot, can you post your compose logs please ?

**Comment by davidrot** [comment]
Hi @crazy-max ,

thank you for your fast response. I was already to tired yesterday. I've used mistakenly you final docker from https://hub.docker.com/r/crazymax/matomo/ and got this error. Ups...

I've started the container with following command

`docker run -d -p 127.0.0.1:80:80 crazymax/matomo`

**Comment by crazy-max** [comment]
You don't have a database running up if you only use `crazymax/matomo`, I suggest to use docker-compose like explained here : https://github.com/crazy-max/docker-matomo#docker-compose

**Comment by OKNoah** [comment]
@crazy-max I suppose the DB is also not included with the Kubernetes install files?
