### ISSUE TITLE
Update to 4.16.0 or even 5.0.0 ?

### ISSUE THREAD

**Issue by rafaelmaeuer** [crazy-max/docker-matomo#148]
### Description

From the official [changelog](https://matomo.org/changelog/) there is [v4.16.0](https://matomo.org/changelog/matomo-4-16-0/) available from 2023-11-28 and even [v5.0.0](https://matomo.org/changelog/matomo-5-0-0/) from 2023-12-19. How about updating to the latest version?

**Comment by Francis-Nalta** [comment]
Hello, very good matomo stack ! running well :)

Any plan to upgrade to matomo 5.0.0 ?

**Comment by rafaelmaeuer** [comment]
I created a feature-request in https://github.com/crazy-max/docker-matomo/issues/151.
