### ISSUE TITLE
Update to v5.0.0 or v5.0.1

### ISSUE THREAD

**Issue by rafaelmaeuer** [crazy-max/docker-matomo#151]
### Description

From the official [changelog](https://matomo.org/changelog/) there is [v5.0.0](https://matomo.org/changelog/matomo-5-0-0/) available from 2023-12-19 and even [v5.0.1](https://matomo.org/changelog/matomo-5-0-1/) from 2024-01-05. How about updating to the latest version?

**Comment by crazy-max** [comment]
PR welcomed

**Comment by rafaelmaeuer** [comment]
if anyone else won't to wait for v5, I forked this repo and re-published my own version on dockerhub:
https://github.com/rafaelmaeuer/docker-matomo/ or https://hub.docker.com/r/rafaelmaeuer/matomo

Feel free to use it, @crazy-max I hope this doesn't disturb you in any way?

**Comment by crazy-max** [comment]
> Feel free to use it, @crazy-max I hope this doesn't disturb you in any way?

That's fine don't worry
