### ISSUE TITLE
No config.ini.php

### ISSUE THREAD

**Issue by Braintelligence** [crazy-max/docker-matomo#2]
Trying to run this I get no config.ini.php 

Log says:
```
The configuration file {/data/config/config.ini.php} has not been found or could not be read.
Please check that /data/config/config.ini.php is readable by the user 'docker'.
```

Not even the /var/www/config contains this file.

Connecting to the site shows this error:
`SQLSTATE[HY000] [2002] No such file or directory`

Any ideas?

**Comment by Braintelligence** [comment]
Restarting the container made a config.ini.php appear in /data but not in /var/www/html/ . The SQLSTATE error remains.

**Comment by Braintelligence** [comment]
Okay, so I had to manipulate the config.ini.php in /data myself via shell and make sure it was chowned to docker:docker ...

Why is the official docker image at least allowing to spin up the website and put in the database configuration there and this one isn't?

**Comment by crazy-max** [comment]
Hi @Braintelligence,

The message that the configuration file has not been found is normal the first time you run the image because no installation has been done yet.

In order for the config. ini. php file to be generated, you must connect to the url filled in via the `SITE_URL' environment variable the first time :

![image](https://user-images.githubusercontent.com/1951866/36664355-b9680b62-1ae4-11e8-883f-fceab04bd6a6.png)

**Comment by Braintelligence** [comment]
Hi @crazy-max ,

like I said, when connecting to the SITE_URL website I got Matomo with the SQLSTATE error.

Maybe my use-case is special. The database container I linked was not mariadb but mysql and it already contained Piwik 3.2.0 data.

It worked after manually editing the config.ini.php, though. It had no database block.

**Comment by crazy-max** [comment]
@Braintelligence,

All right, I see. I hadn't thought of a migration like that. I will add information in README for the installation phase. Thanks for your input.

**Comment by Braintelligence** [comment]
So it really was because of my use-case? I see! Thanks for clarifying 😺.

**Comment by crazy-max** [comment]
@Braintelligence Yes, and I think there was a permission problem that I solved in the last version of the image if you want to test it

**Comment by Braintelligence** [comment]
I'll test it for another instance sometime in the future; for now the one I fixed by modifying the config.ini.php is working and I won't touch what's working 😜

**Comment by Braintelligence** [comment]
Hey @crazy-max - not sure why (one possible reason being a full disk perhaps) but the `config.ini.php` only contained one line now. (Don't know when this happened.) I had to touch the `config.ini.php` again to put database config in there.

**Comment by Braintelligence** [comment]
Hello @crazy-max I think i have the same issue AGAIN.
The `config.ini.php` in `/data` contains only one line and there is no `config.ini.php` in /var/www/config

I mounted /data to a docker volume, how come the config doesn't seem to persist in some cases?

**Comment by crazy-max** [comment]
@Braintelligence 

> The `config.ini.php` in `/data` contains only one line and there is no `config.ini.php` in /var/www/config

Can you open a new issue about this please?
