### ISSUE TITLE
docker swarm not installing

### ISSUE THREAD

**Issue by gp187** [crazy-max/docker-matomo#21]
Every time I try to run the docker swarm config, even with default values, on a freshly installed Ubuntu 18 server I get this 

`error while interpolating services.matomo.deploy.replicas: failed to cast to expected type: strconv.Atoi: parsing "": invalid syntax`

**Comment by crazy-max** [comment]
Post your docker-compose.yml, .env and matomo.env files without sensitive data. Also have you following the [README](https://github.com/crazy-max/docker-matomo/blob/master/examples/swarm/README.md) ?

**Comment by webgps** [comment]
+1 I have the same error with default, unchanged files, only root dir is changed in .env

**Comment by webgps** [comment]
> +1 I have the same error with default, unchanged files, only root dir is changed in .env

Figured it out! You have to download all the images  manually referenced by the compose file after that installed flawlessly!
