### ISSUE TITLE
How-To Install as PHP-FPM Container only

### ISSUE THREAD

**Issue by continga** [crazy-max/docker-matomo#28]
Hey @crazy-max this project looks really promising, nice one!

I have a question though. We are currently running Matomo using a stack based on the `matomo:fpm-alpine` containers, so directly using the official Matomo images. Running a PHP-FPM container directly without any additional stuff (e.g. NGINX) offers us the possibility to make our Matomo installation highly customizable (through a custom Dockerfile), whilest the container being really small and not doing unneeded stuff.

We are basically using an external reverse proxy which we grant access to the `/var/www/html` volume of the `fpm-alpine` container, and we fastcgi proxy pass all requests to non-known/non-static/.php-files to the fpm container using unix sockets, which basically leaves us with a very small, highly effective setup.

We would really like to use your Matomo images for our setup due to the included "side car" functionality, because we are currently doing this via the default browser-requests of Matomo, and doing it via a container-based setup is much more effective. 

The complexity of your images is just keeping us from doing so, we don't need an included NGINX, basically we just need a running `php-fpm` instance which handles the Matomo stuff, and a "sidecar" container which then handles the cronjobs etc... 

Is the documentation lacking this kind of information, is it somehow possible already? Do you understand what we are trying to archieve? 

I would be willing to archieve that goal by submitting pull requests myself, I just need to understand whether this would be a goal you would be targeting, how we would do it (maybe build separate images for normale use and for nginx-full-use), etc...

Thanks for an answer, and if you got any questions regarding our setup, don't hesitate to ask!

Edit: Maybe as an alternative, if this would be going way beyond the purpose of this image: Do you have any suggestions to how we could easily (i.e. future-proof, and with as little hacking as possible) adapt the `matomo:fpm-alpine` image to be a "sidecar" container like you have one? Basically that would already solve our problems, and maybe we could get this into the documentation of the official image then together.

**Comment by crazy-max** [comment]
Hi @continga,

This image contains nginx to avoid any frustration of users to set up and manage themselves the configuration of a reverse proxy. It also provides a certain stability in relation to the prerequisites of the Nginx configuration. So I don't plan to add an image that only goes through PHP-FPM.

However, you can add another reverse proxy above this image as in [this example with Traefik](https://github.com/crazy-max/docker-matomo/blob/master/examples/compose/docker-compose.yml#L4-L33).

Feel free to open a PR if you willing add a customized Nginx reverse proxy on top of this image or if you want more customization of the embedded reverse proxy through env vars for example.

Thanks for your support
