### ISSUE TITLE
Missing Config for "login_session_not_remembered_idle_timeout"

### ISSUE THREAD

**Issue by dhemeier** [crazy-max/docker-matomo#29]
### Behaviour
Hey, found out a strange behavior. So currently no upgrade / restart of the Container is possible. Always ends in a wrong config file.

#### Steps to reproduce this issue

1. Start your docker container
2. Search for the config variable `login_session_not_remembered_idle_timeout` in /data/global.ini.php

#### Expected behaviour

`login_session_not_remembered_idle_timeout`  should be set correctly

#### Actual behaviour

The global.ini.php does not contain the default value for the `login_session_not_remembered_idle_timeout` after starting the container:

```
/data/config # cat global.ini.php | grep session_
session_save_handler = dbtable
```

The current file `global.ini.php` shipped  with your version is copied in your `entrypoint.sh` line 75 from /var/www/config to /data/config BEFORE calling the update:
```
# Copy global config
cp -Rf /var/www/config /data/
```

But Matomo seems to fix this error on `core:update` calls and sets this variable to the `/var/www/config/global.ini.php` but then its to late (always copied to /data).

I think in the latest core files the variable should be set per default and then the container would work. So could you please rebuild your image to include per default the correct global.ini.php config? Its not your fault I know ;-)

##### UPDATE
Checked currently the original Release 3.11.0 (https://github.com/matomo-org/matomo/releases/tag/3.11.0) -> global.ini.php contains the variable correctly.

#### Workaround
You could set this variable to your own `config.ini.php` to resolve this issue.

**Comment by dhemeier** [comment]
I am so sorry, I fu**ed up myself. As you could expect I use Kubernetes to start the container. For this configuration I had one Pod with two containers (one cron and one for regular web access) -> the cron was not updated and still on version 3.9.x

So after start the cron overwrites the (correct) config from the 3.11.0 to the outdated 3.9.X config. All in your configuration is absolutely correct.

**Comment by crazy-max** [comment]
No problem @dhemeier :ok_hand:
Thanks for the head up!
