### ISSUE TITLE
Deleting pods cause of lose part of settings

### ISSUE THREAD

**Issue by DeamonMV** [crazy-max/docker-matomo#31]
### Behaviour

I made worked Matomo. Configured conntion to DB and pass all configuration steps. After this i configured Geolocations - downloaded MaxMind DB and chose using of Php module of Geolocation.
But after I deleted pod with matomo i lose this configuration.

#### Steps to reproduce this issue

1. Deploy matomo
2. Configure Geolocation to use GeoIP2 (PHP) with MaxMind DB
3. Delete pod with matomo
4. Check configuration of Geolocation

#### Expected behaviour

After pod was deleted, all configuration should be on the place.

#### Actual behaviour

Configuration of Geolocation gone after pod was deleted.

### Configuration

* Kubernetes version 1.14.3
* Rook as a storage
* matomo:v3.12.0

### Logs

```
 kubectl logs -f memento-matomo-7cc7969cf-j2kr8 matomo
Setting PHP-FPM configuration...
Setting OpCache configuration...
Setting Nginx configuration...
Setting SSMTP configuration...
WARNING: SSMTP_HOST must be defined if you want to send emails
Initializing Matomo files / folders...
Checking Matomo plugins...
Checking Matomo user-misc folder...
Fixing permissions...
Setting Matomo log level to WARN...
Setting [log] log_level = "WARN"... done.
Upgrading and setting Matomo configuration...

Everything is already up to date.

Setting [General] minimum_memory_limit = "-1"... done.
2019-11-05 15:35:24,436 INFO Included extra file "/etc/supervisord/matomo_watch_plugins.conf" during parsing
2019-11-05 15:35:24,436 INFO Included extra file "/etc/supervisord/nginx.conf" during parsing
2019-11-05 15:35:24,437 INFO Included extra file "/etc/supervisord/php.conf" during parsing
2019-11-05 15:35:24,437 INFO Set uid to user 0 succeeded
2019-11-05 15:35:24,487 INFO RPC interface 'supervisor' initialized
2019-11-05 15:35:24,489 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-11-05 15:35:24,490 INFO supervisord started with pid 1
2019-11-05 15:35:25,493 INFO spawned: 'nginx' with pid 22
2019-11-05 15:35:25,498 INFO spawned: 'php' with pid 23
2019-11-05 15:35:25,501 INFO spawned: 'matomo_watch_plugins' with pid 24
2019/11/05 15:35:25 [notice] 22#22: using the "epoll" event method
2019/11/05 15:35:25 [notice] 22#22: nginx/1.17.5
2019/11/05 15:35:25 [notice] 22#22: built by gcc 8.3.0 (Alpine 8.3.0)
2019/11/05 15:35:25 [notice] 22#22: OS: Linux 4.9.0-11-amd64
2019/11/05 15:35:25 [notice] 22#22: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/11/05 15:35:25 [notice] 22#22: start worker processes
2019/11/05 15:35:25 [notice] 22#22: start worker process 27
2019/11/05 15:35:25 [notice] 22#22: start worker process 28
Setting up watches.
Watches established.
[05-Nov-2019 15:35:25] NOTICE: fpm is running, pid 23
[05-Nov-2019 15:35:25] NOTICE: ready to handle connections
2019-11-05 15:35:26,592 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-05 15:35:26,592 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-05 15:35:26,593 INFO success: matomo_watch_plugins entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by crazy-max** [comment]
Any idea @dhemeier?

**Comment by dhemeier** [comment]
Hello @DeamonMV 

this behavior is "correct". When you use the GeoIp 2 (PHP) implementation, then you normally install the database to the `misc` folder located inside the container on `/var/www/misc`. This directory is not covered by any persistent data volume.

**Solution**
You need to upload the Database to the `/data/misc/user/` directory. After that and a pod delete, the entrypoint.sh script of the container should symlink/copy the content to `/var/www/misc/user` and make it accessible to Matomo.

Then you should be able to configure the plugin and use it without problems after a Pod deletion.

**Alternative Option**
Use the build in geo-database from the php-library and set configuration to Geo Ip 2 (HTTP-Server Module). This should work without any configuration.

Let me know if this helps you.

Dennis

**Comment by DeamonMV** [comment]
Hello @dhemeier 

Thanks for help. I'll check it and will write here what i got.

**Comment by DeamonMV** [comment]
@dhemeier 

It's now working as you described 

I created just a file in /data/misc/user and deleted pod. After pod started nothing was add to /var/www/misc/user

I checked entrypoint.sh and found this:

```
# Check user folder
echo "Checking Matomo user-misc folder..."
if [ ! -d /data/misc/user ]; then
  if [[ ! -L /var/www/misc/user && -d /var/www/misc/user ]]; then
    mv -f /var/www/misc/user /data/misc/
  fi
  ln -sf /data/misc/user /var/www/misc/user
fi
```

This code do not create or make link to /var/www/misc/user

**Comment by DeamonMV** [comment]
I was not right in details, but in general it's not working.
Entrypoint create symlink, but she not work, she more like empty.

```
/data/misc/user # ls /var/www/misc/user/
index.html  user
/data/misc/user # ls /var/www/misc/user/ -la
total 12
drwxr-xr-x    1 nginx    nginx         4096 Nov 28 15:42 .
drwxr-xr-x    1 nginx    nginx         4096 Nov 27 05:32 ..
-rw-r--r--    1 nginx    nginx          170 May 13  2019 index.html
lrwxrwxrwx    1 root     root            15 Nov 28 15:42 user -> /data/misc/user
```

I modified `Check user folder` in this way and had it worked out 

```
# Check user folder
echo "Checking Matomo user-misc folder..."
if [ ! -d /data/misc/user ]; then
  if [[ ! -L /var/www/misc/user && -d /var/www/misc/user ]]; then
    mv -f /var/www/misc/user /data/misc/
  fi
else
  if [[ ! -L /var/www/misc/user && -d /var/www/misc/user ]]; then
    rm -fr /var/www/misc/user
  fi
  ln -sf /data/misc/user /var/www/misc/user
fi
```
The result

```
/var/www # ls -l misc/
total 24
-rw-r--r--    1 nginx    nginx          341 May 13  2019 How to install Matomo.html
drwxr-xr-x    2 nginx    nginx         4096 May 13  2019 composer
drwxr-xr-x    2 nginx    nginx         4096 Oct 29 04:16 cron
drwxr-xr-x    2 nginx    nginx         4096 Nov 27 05:32 log-analytics
drwxr-xr-x    2 nginx    nginx         4096 Jul  1 11:27 others
drwxr-xr-x    2 nginx    nginx         4096 May 13  2019 proxy-hide-piwik-url
lrwxrwxrwx    1 root     root            15 Nov 28 15:49 user -> /data/misc/user
/var/www # ls -l misc/user/
total 4
-rw-r--r--    1 nginx    nginx          170 May 13  2019 index.html
-rw-r--r--    1 nginx    nginx            0 Nov 28 15:44 sdf
/var/www # ls -l /data/misc/user/
total 4
-rw-r--r--    1 nginx    nginx          170 May 13  2019 index.html
-rw-r--r--    1 nginx    nginx            0 Nov 28 15:44 sdf
```

**Comment by crazy-max** [comment]
Hi @DeamonMV, looks like right for this, I will take a look on this asap. Thanks for your feedback.

**Comment by DeamonMV** [comment]
@crazy-max Thanks. 
If you will have time please check `Plugin` section. On a quick look and my last tests, seems that plugins also do not persist. 

But anyway I'll perform such test, and let you know.

**Comment by dhemeier** [comment]
@DeamonMV 
I currently use self installed plugins and its working. Also after a Pod restart ;-) - But maybe some other cases are not working...

**Comment by crazy-max** [comment]
@DeamonMV Should be fixed for user misc data but on the other hand everything looks ok for plugins.

**Comment by DeamonMV** [comment]
Unfortunately this fix didn't help. 
Problem is Matomo wait to see `GeoLite2-City.mmdb` in `/var/www/misc` not in `/var/www/misc/user/`

I tried to copy `GeoLite2-City.mmdb` to `/var/www/misc/user`, but it's not working.

**Comment by crazy-max** [comment]
@DeamonMV GeoIP 2 databases are already available [through Nginx](https://github.com/crazy-max/docker-matomo#geoip-2) and they are updated through our [sidecar cron container](https://github.com/crazy-max/docker-matomo/blob/master/examples/compose/docker-compose.yml#L80).
Do you want GeoIP 2 to be managed through PHP instead?

**Comment by DeamonMV** [comment]
I think, I'll just use Geo over HTTP Server Module. It's seems work as perfect as Php Module. Thanks

But with Plugins I faced a problem. 

For example.
- In the fresh matomo installation(i'm using a last your update of matomo from dockerhub) I installed AOM plugin. 
- If we go to container, we can see that in folder ` /var/www/plugins/` `AOM` plugins is present. And folder `/data/plugins` is empty
- If delete a container, after matomo is up, he see that there are should be AOM plugin, but because `/var/www/plugins/` does not contain `AOM` folder anymore. And matomo shows this warning

>The following plugins are not compatible with Matomo 3.13.0 and could not be loaded: AOM.
>You can update or uninstall these plugins on the Manage Plugins page.

**Comment by dhemeier** [comment]
@DeamonMV I mentioned Geo over HTTP in my first post ;-) 

**Plugin Installations**
I tested a little bit with the plugin handling. Currently, you need to **manually copy the installed plugin directory**  to `/data/plugins`. When you do this and kill the pod, the init process symlinks the detected plugins to `/var/www/plugins` and all should work fine. 

I also played a little bit with a new feature called `MATOMO_PLUGIN_COPY_DIR ` @see https://github.com/matomo-org/matomo/pull/14537

But this currently not working because then we need to place the `/data/plugins` directory inside the webroot to gain access from the webserver which needs a little bit more rewriting of the existing code. @crazy-max - Maybe we should rewrite the plugin handling and use the new features?

**Comment by crazy-max** [comment]
> Maybe we should rewrite the plugin handling and use the new features?

Hum interesting I will make some tests on this, thanks @dhemeier !

**Comment by crazy-max** [comment]
@dhemeier Ok I think I will use [multiple plugin paths support](https://github.com/matomo-org/matomo/pull/14051) through `MATOMO_PLUGIN_DIRS=/data/plugins;/var/www/plugins`

**Comment by crazy-max** [comment]
@DeamonMV @dhemeier Should be solved with latest release of this image now.
