### ISSUE TITLE
Worth doing releases?

### ISSUE THREAD

**Issue by mlissner** [crazy-max/docker-matomo#32]
Hi, I'm a happy user of this, but one thing that's tricky is staying up to date. You do a great job keeping the files here up to date, but I don't have a good way of knowing when there are changes. 

I have used Github's "Watch" repository thing to keep up to date, but it only tells me when there are new "conversations" or "releases", I think.

I imagine this makes more work for you, but would it be possible to do releases so that folks like me can stay up to date on our ends? 

Right now I get the notice from Matomo that there's a new version, I come here too soon and this isn't updated, and I have to remember to come back later.

**Comment by mlissner** [comment]
Oh, and thank you again for all the work on this!

**Comment by crazy-max** [comment]
Hi @mlissner,

> but I don't have a good way of knowing when there are changes.

You can use [Diun](https://github.com/crazy-max/diun), it's another project I maintain that allows you to be notified when a Docker image is updated.

**Comment by mlissner** [comment]
It's cool that you have that, and perhaps I'm just not deep enough in the containerization world, but it's a lot for me to run another image just for this purpose.

**Comment by mlissner** [comment]
I did find this: https://docker-notify.com/. No idea if/how it works, but I'm going to give it a try. It's annoying Github doesn't offer a better solution for this than releases (which I imagine would be a lot of work).
