### ISSUE TITLE
Docker Hub repository not found

### ISSUE THREAD

**Issue by Swiftwork** [crazy-max/docker-matomo#33]
### Behaviour

Crazymax Matomo repostitory shows 404

#### Steps to reproduce this issue

1. Go to https://hub.docker.com/r/crazymax/matomo

#### Expected behaviour

> That the repository images can be found

#### Actual behaviour

> 404 the page you have requested is not found and docker pull times out

### Configuration

* All systems presumably

**Comment by crazy-max** [comment]
@Swiftwork Looks like this is an UI issue on Docker Hub and it's happening only on mobile on my side but looks ok on dekstop:

![image](https://user-images.githubusercontent.com/1951866/73532169-702d2000-441c-11ea-9995-ed6757bf4cc9.png)

Feel free to contact Docker Hub about this.

**Comment by Swiftwork** [comment]
Have you tried to pull an image? I experience the same issue there. Maybe your desktop cached the site or you are logged in? Try incognito :)

**Comment by crazy-max** [comment]
@Swiftwork I have already tried in incognito and it works for me. I can pull the image too:

```
$ docker pull crazymax/matomo
Using default tag: latest
latest: Pulling from crazymax/matomo
4167d3e14976: Pull complete
db94a93dfca0: Pull complete
41fd2d4ea644: Pull complete
aa53fee90208: Pull complete
c21c1390b6df: Pull complete
ff0a35911de9: Pull complete
629113d0645c: Pull complete
8d29d64eb7c6: Pull complete
f65e489ab21d: Pull complete
d94678b3bc95: Pull complete
Digest: sha256:bbcc096b2088d14b916bff4963320aa6acb2820b2d073b2587bff180ce54f471
Status: Downloaded newer image for crazymax/matomo:latest
docker.io/crazymax/matomo:latest
```

**Comment by Swiftwork** [comment]
I checked my phone and it was accessible even though my desktop wasn't. Now docker pull worked for me too. I guess docker hub had some kind of hiccup. Thanks for taking your time and looking into it.

Kind regards Erik

**Comment by SystemZ** [comment]
I had this same issue right know.
Some resources loaded on docker hub are blacklisted on some adblock list.
Hub doesn't recognize this properly and it's showing 404 instead.
Turning off adblock resolved this issue.
