### ISSUE TITLE
nginx.conf set_real_ip_from setting has wrong netmask.

### ISSUE THREAD

**Issue by drcain1** [crazy-max/docker-matomo#35]
The set_real_ip_from setting should be "0.0.0.0/0" to grab all upstream proxies. Not "0.0.0.0/32"

>     ## Handling of IPs in proxied and load balancing situations
>     set_real_ip_from 0.0.0.0/32;

change set_real_ip_from 0.0.0.0/32;
to set_real_ip_from 0.0.0.0/0;

I have overridden this locally and GeoIP2 works afterwards, otherwise it will just detect Dockers' REMOTE_ADDR.

Thank you.

**Comment by crazy-max** [comment]
@drcain1 You can already change this through `REAL_IP_FROM` [env var](https://github.com/crazy-max/docker-matomo#environment-variables) to fit your needs.

**Comment by drcain1** [comment]
Oh, I missed that part.
Added the internal docker network 172.16.0.0/12 and everything works as expected.
Thanks for the great work with the Docker image 👍
