### ISSUE TITLE
GeoIp2 region not showing

### ISSUE THREAD

**Issue by m-straub** [crazy-max/docker-matomo#37]
Hi,

the default server variable name for region geo tracking doesn't match with matomos default.
Is: MM_REGION
Should be (matomo default): MM_REGION_CODE

To fix this I had to change the setting for the "region code" in matomo to "MM_REGION".

**Comment by crazy-max** [comment]
Hi @m-straub, thanks for your input, I will fix that.

**Comment by crazy-max** [comment]
@m-straub Should be fixed now
