### ISSUE TITLE
Use IPv6 GeoIP databases

### ISSUE THREAD

**Issue by sbruder** [crazy-max/docker-matomo#4]
With the currently used GeoIP databases, only IPv4 addresses get looked up properly. For IPv6 addresses, Matomo falls back to language detection due to missing values in the fastcgi geoip parameters.
According to the [Documentation of the nginx module](https://nginx.org/en/docs/http/ngx_http_geoip_module.html), the the module can – when an IPv6 database is present – look up both IPv6 and IPv4 (as v6-mapped address) in the database. I tried replacing the IPv4-only databases with the combined ones and it worked correctly.

The URLs of the IPv6/combined databases are:

 * http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz (Country)
 * http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz (City)

Related part of the Dockerfile:
https://github.com/crazy-max/docker-matomo/blob/8a2f0e7bb97290e9ed5bdd48778af35300eb0e79/Dockerfile#L38-L41

**Comment by crazy-max** [comment]
Good suggestion @sbruder thanks !

**Comment by crazy-max** [comment]
@sbruder Solved in latest image
