### ISSUE TITLE
Homepage missing from docs

### ISSUE THREAD

**Issue by psiegman** [crazy-max/docker-matomo#6]
I've started the docker-compose, output looks good.
Then it says:

> Open your browser to install Matomo through the wizard

However, it doesn't say which url to go to.

From lsof -i:80 it looks like port 80 is being served by this docker-compose.

I've tried 'http://localhost/', 'https://localhost', 'http://127.0.0.1', 'http://localhost/matomo', but they all give me a 404.

**Comment by crazy-max** [comment]
It depends on your infrastructure. The container cannot guess this URL / IP.
What is your host OS ?

**Comment by psiegman** [comment]
Host OS is MacOS, this is my laptop.
Should I add a virtualhost mapping somewhere ?

**Comment by crazy-max** [comment]
Ok if it's your local computer, http://127.0.0.1 should work if you map the port on your host in the traefik service.

**Comment by psiegman** [comment]
Going to http://127.0.0.1 didn't work for me.

In the meantime I have found a working solution: I deployed matomo to a Kubernetes cluster, and that works for me.

If you can point me to an explanation on how to map the port on the host in the traefik service I can see if that works, so we can update the documentation.
If you want to leave it at this that's fine by me too.

Thanks for your help.

**Comment by crazy-max** [comment]
Something like that should work :

```
ports:
  - target: 80
    published: 8080
    protocol: tcp
    mode: host
```
