### ISSUE TITLE
Document how to upgrade with big migrations

### ISSUE THREAD

**Issue by mlissner** [crazy-max/docker-matomo#61]
### Behaviour

I just upgraded to matomo 4.0, and I ran into something that never happened before. When I ran this:

    sudo docker service update k3do --image crazymax/matomo

It seemed like it had some sort of timeout issue doing the upgrade. I watched the logs and saw that matomo was running SQL migrations, but when it neared the end there was one migration that was particularly slow. Whenever it got there, it seemed like docker would give up on the migration and start it all over. That'd get as far as the same migration, and it'd get stuck there again. 

This loop repeated nearly endlessly, so I eventually killed the service, and recreated it. 

I'm not sure the solution here. Maybe your upgrade script could be tweaked to have some sort of "I'm still working" ping it sends to docker? Maybe there's a command line flag the docs should recommend for doing upgrades, so that docker has a longer timeout? 

This wasn't a great experience, so I'm trying to brainstorm ways to make it better for others. 

Thank you as always.

**Comment by crazy-max** [comment]
@mlissner  If the migration takes too much time you can:

```shell
docker service rm k3do
docker service create k3do --stop-grace-period 1h ...
```

I remove and create the service to be able to change the initial definition of `--stop-grace-period`.
See https://docs.docker.com/engine/reference/commandline/service_create/#options.
