### ISSUE TITLE
GeoIP2 not detecting city, etc

### ISSUE THREAD

**Issue by PhyxionNL** [crazy-max/docker-matomo#62]
Using matomo 4.0.4. image (previous versions have the same problem).

phpinfo:

Variable|Value
-- | --
$_SERVER['MM_COUNTRY_IN_EU'] | no value
$_SERVER['MM_COUNTRY_NAME'] | no value
$_SERVER['MM_COUNTRY_CODE'] | no value
$_SERVER['MM_REGION_NAME'] | no value
$_SERVER['MM_REGION_CODE'] | no value
$_SERVER['MM_REGION_GEONAMEID'] | no value
$_SERVER['MM_REGISTERED_COUNTRY_IN_EU'] | no value
$_SERVER['MM_REGISTERED_COUNTRY_NAME'] | no value
$_SERVER['MM_REGISTERED_COUNTRY_ISO'] | no value
$_SERVER['MM_REGISTERED_COUNTRY_GEONAMEID'] | no value
$_SERVER['MM_POSTAL_CODE'] | no value
$_SERVER['MM_LOCATION_TIMEZONE'] | no value
$_SERVER['MM_LOCATION_METROCODE'] | no value
$_SERVER['MM_LONGITUDE'] | no value
$_SERVER['MM_LATITUDE'] | no value
$_SERVER['MM_LOCATION_ACCURACY_RADIUS'] | no value
$_SERVER['MM_COUNTRY_GEONAMEID'] | no value
$_SERVER['MM_CONTINENT_NAME'] | no value
$_SERVER['MM_CONTINENT_GEONAMEID'] | no value
$_SERVER['MM_CITY_GEONAMEID'] | no value
$_SERVER['MM_CITY_NAME'] | no value
$_SERVER['MM_ORG'] | no value
$_SERVER['MM_ISP'] | no value

The geoip files are updated correctly and exist:

> /data/geoip # ls -l
total 71203
-rwxr-xr-x    1 root     root       6607440 Dec  9 12:07 GeoLite2-ASN.mmdb
-rwxr-xr-x    1 root     root      62306534 Dec  9 12:07 GeoLite2-City.mmdb
-rwxr-xr-x    1 root     root       3996411 Dec  9 12:07 GeoLite2-Country.mmdb

It's running behind a reverse proxy. If I enable DBIP / GeoIP 2 (Php), it's working and all information is correctly returned. 
I wouldn't mind keeping it on PHP, but this is not ideal as it automatically goes back to DBIP / GeoIP 2 (HTTP Server Module) after image upgrade.

Any idea what's going wrong here with GeoIP2? The plugin is activated and the server variables have been configured. I can see HTTP_X_FORWARDED_FOR being sent as well.

**Comment by crazy-max** [comment]
@PhyxionNL https://github.com/crazy-max/docker-matomo#geoip2

**Comment by PhyxionNL** [comment]
I already have everything set up according to that guide, but it does not work. I'm now using the (Php) version where its db is mapped so it works after upgrading. I'd rather use the server module, but I don't know how to get it working, in phpinfo everything is empty too.

**Comment by crazy-max** [comment]
@PhyxionNL Can you make a screenshot of `GeoIP 2 (HTTP Server Module) in System > Geolocation`, like the one in https://github.com/crazy-max/docker-matomo#geoip2

**Comment by PhyxionNL** [comment]
Yes, of course (obviously it's not enabled as it doesn't detect anything):

![image](https://user-images.githubusercontent.com/7643972/104759671-90a2d700-5760-11eb-903b-481e3cbe6712.png)

The other one (goes on with default stuff):

![image](https://user-images.githubusercontent.com/7643972/104759753-ac0de200-5760-11eb-9c22-adbd3df6cc3e.png)

**Comment by crazy-max** [comment]
@PhyxionNL Cannot reproduce. It works fine for me with `DBIP / GeoIP2 (HTTP Server Module)` (current location found):

![image](https://user-images.githubusercontent.com/1951866/104760918-f9d31c00-5759-11eb-94a4-7715e881ca4a.png)

Maybe a misconfiguration on your side. Please create a proper [bug report](https://github.com/crazy-max/docker-matomo/issues/new?assignees=&labels=&template=bug_report.md).

**Comment by PhyxionNL** [comment]
Here's that info (I didn't list it as a bug initially as I wasn't sure what the reason was):

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.0, build 7287ab3
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.27.4, build 40524192
* Platform (Debian 9, Ubuntu 18.04, ...) : Windows 10 20H2
* Include all necessary configuration files : `docker-compose.yml`, `.env`: Identical to https://github.com/crazy-max/docker-matomo/tree/master/examples/compose (without traefik and msmtpd)

### Docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 9.713GiB
 Name: docker-desktop
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 113
  Goroutines: 101
  System Time: 2021-01-15T18:48:17.8156421Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

I've recreated it a couple of times already with various configurations, but the result remains the same. Are you running it behind a reverse proxy? Although I'm not sure that's the reason for it.

**Comment by crazy-max** [comment]
@PhyxionNL 

> Windows 10 20H2

I assmue you're on WSL2?

**Comment by PhyxionNL** [comment]
Yes, but WSL1 on my other machine has the same problem.

**Comment by crazy-max** [comment]
Ok so I don't think that's an issue with this image but the WSL network configuration. I suggest to open an issue on [WSL repo](https://github.com/microsoft/WSL/issues).

**Comment by PhyxionNL** [comment]
I'm not sure that's the case as the other geo ip options are working fine.

**Comment by crazy-max** [comment]
GeoIP values are populated based on the remote IP accessing the web server. In your case the remote IP cannot be resolved to a public one because of WSL networking. See container logs to find out.
