### ISSUE TITLE
Matomo keeps forgetting (database) config if VM fails (due to low memory for example)

### ISSUE THREAD

**Issue by Braintelligence** [crazy-max/docker-matomo#63]
#### Steps to reproduce this issue

1. Run Crazymax Matomo as per docker-compose example
2. Reach automatic kill of mysql process due to OOM
3. docker-compose down and up again

#### Expected behaviour

> Matomo keeps config, since /data is being persisted

#### Actual behaviour

> Matomo loses config, you have to reinitialize with empty /data or add your own config.php (since it isn't getting created)

This Error pops up: 

Cannot connect to the database:
SQLSTATE[HY000] [2002] No such file or directory

### Configuration

* Docker version (type `docker --version`) : 19.03.12
* Docker compose version if applicable (type `docker-compose --version`) : 1.26.2
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.04
* System info (type `uname -a`) : 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ... - they are like in the docker-compose example

### Docker info

```
> Output of command `docker info`
SSH currently not enabled, will provide if necessary. Can't copypaste.
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
SSH currently not enabled, will provide if necessary. Can't copypaste.
```

**Comment by Braintelligence** [comment]
I deleted content of /data and reinitialized again after a `docker-compose pull`. Now config.ini.php seems to be created and persisted. 🤷 
Will close for now until maybe OOM issue comes up again.

**Comment by missy0u** [comment]
The same problem

**Comment by missy0u** [comment]
Twice consecutively within a month...
