### ISSUE TITLE
How to do most recent upgrade

### ISSUE THREAD

**Issue by mlissner** [crazy-max/docker-matomo#65]
### Behaviour

I'm not sure how to upgrade, sorry!

#### Steps to reproduce this issue

1. Install matomo using this image
2. Note that recent docs say:

    > As the Docker container now runs as a non-root user, you have to first stop the container and change permissions to data volume:

3. Try to figure that out

#### Expected behaviour

I guess I just need a little more detail here. The upgrade notes say that you need to run:

chown -R 1000:1000 data/

Which makes sense, except I don't know where that `data/` volume is. 

Looking around, I do seem to have some stuff in `/var/lib/docker/volumes/`:

```
drwxr-xr-x 3 root root  4096 Jul 15  2019 matomo_db
drwxr-xr-x 3 root root  4096 Jul 15  2019 matomo_matomo
-rw------- 1 root root 65536 Feb 18 22:17 metadata.db
```

But I'm a bit hesitant to mess with those permissions if that's not the right thing. Should I run something like:

```
sudo chown -R 1000:1000 /var/lib/docket/volumes/matomo_matomo
sudo chown -R 1000:1000 /var/lib/docket/volumes/matomo_db
```

Is that right right idea here? 

Thank you for the wonderful package and all your work.

**Comment by crazy-max** [comment]
@mlissner 

> But I'm a bit hesitant to mess with those permissions if that's not the right thing. Should I run something like:

No you shouldn't. As you are using named volumes with it seems docker-compose:

```shell
$ docker volume ls
DRIVER    VOLUME NAME
local     matomo_matomo
local     matomo_db
```

You can create a tmp container to change perms on `/data` with the following command:

```shell
# stop compose stack first
$ docker-compose down
# create tmp container with busybox and change perms inside it
$  docker run --rm -it -v "matomo_matomo:/data" busybox sh
/ # chown -R 1000:1000 /data
/ # ls -al /data
total 32
drwxr-xr-x    8 1000     1000          4096 Feb 26 09:14 .
drwxr-xr-x    1 root     root          4096 Feb 26 09:21 ..
drwxr-xr-x    2 1000     1000          4096 Feb 26 09:14 config
drwxr-xr-x    2 1000     1000          4096 Feb 26 09:14 geoip
drwxr-xr-x    3 1000     1000          4096 Feb 26 09:14 misc
drwxr-xr-x    2 1000     1000          4096 Feb 26 09:14 plugins
drwxr-xr-x    2 1000     1000          4096 Feb 26 09:14 session
drwxr-xr-x    2 1000     1000          4096 Feb 26 09:14 tmp
```
