### ISSUE TITLE
4.2.0+ does not have MATOMO_PLUGIN_DIRS environment variable set for console

### ISSUE THREAD

**Issue by noderat** [crazy-max/docker-matomo#67]
### Behaviour

The alternate plugin path is currently only set through the php-fpm configuration file. This means that plugins are unable to be activated through the matomo CLI console tool.

#### Steps to reproduce this issue

1. Install plugin into /data/plugin's volume
2. Start container (which will symlink /data/plugins to /var/www/matomo/data-plugins)
3. Exec into running container with `console plugin:activate <pluginName>` which will fail
    ```
    bash-5.1# console plugin:activate QueuedTracking
    ERROR [2021-03-05 15:56:35] 7681  Uncaught exception: /var/www/matomo/core/Plugin/Manager.php(684): Plugin 
    'QueuedTracking' cannot be found in the filesystem in plugins/ directory.
    Plugin 'QueuedTracking' cannot be found in the filesystem in plugins/ directory.
    ```
4. Export the MATOMO_PLUGIN_DIRS variable and try again
    ```
    bash-5.1# export MATOMO_PLUGIN_DIRS="/var/www/matomo/data-plugins;/var/www/matomo/plugins"
    bash-5.1# console plugin:activate QueuedTracking
    Activated plugin QueuedTracking
    ```

**Comment by crazy-max** [comment]
@noderat 

Good catch! Thanks for your feedback I will add the behavior for the CLI too.

**Comment by crazy-max** [comment]
@noderat Should be fixed now
