### ISSUE TITLE
TagManager container javascript not regenerated on all replicas in a load balanced environment

### ISSUE THREAD

**Issue by coolguy357** [crazy-max/docker-matomo#68]
### Behaviour
The TagManager plugin should regenerate the container javascript files when the archive process runs, or when the container is updated. When there are multiple replicas of matomo, only the replica serving the update request will regenerate the container javascript. If we run the matomo container as a `SIDECAR_CRON`, the archival process will only regenerate the container javascript in the sidecar instance of the matomo container.

#### Steps to reproduce this issue

1. deploy in kubernetes with `replicas: 2`
2. enable the TagManager plugin
3. create a TagManager container
4. Note the missing container javascript in one of the replicas. In each replica:
    - exec into matomo container
    - `ls /var/www/matomo/js`

#### Expected behaviour

> Both replicas (re)generate container javascript on archival and/or on updates to the TagManager container

#### Actual behaviour

> Only one replica (re)generates container javascript

**Comment by crazy-max** [comment]
@coolguy357 Thanks for your feedback. Didn't know this behavior of TagManager, I will take a look.

**Comment by crazy-max** [comment]
@coolguy357 We could probably do something [like this](https://github.com/matomo-org/tag-manager/issues/154#issuecomment-461543555) in the `config.php` but we should find a way to merge with the actual `/js`  folder to avoid a new endpoint for TagManager Container on your side. Will think about that.

**Comment by coolguy357** [comment]
@crazy-max Yeah, I considered doing something like that, and running the sidecar as a kubernetes cronjob, aaand a rewrite rule in nginx to go to the `/data/wherever_the_js_storage_is` directory from the `/var/www/matomo/js` web endpoint.

Or just optionally include a cronjob in the matomo container to `console tagmanager:regenerate-released-containers` every once in a while to keep each replica up to date.

**Comment by crazy-max** [comment]
@coolguy357 

> Or just optionally include a cronjob in the matomo container to `console tagmanager:regenerate-released-containers`

This one LGTM.

**Comment by crazy-max** [comment]
See also #69

**Comment by coolguy357** [comment]
@crazy-max that seems to have fixed it. Changes are synced between replicas now with that symlink in the data volume.

**Comment by crazy-max** [comment]
@coolguy357 Ok great, I've published a new release. Enjoy.

**Comment by noderat** [comment]
@crazy-max it looks like `rsync -a` does not work if the destination is a mounted SMB (NTFS) filesystem such as when using azure-files storage provider in kubernetes. The destination file system does not support the permissions and results in this error:
```
Checking Matomo js folder...
rsync: mkstemp "/data/tmp/js/.LICENSE.txt.obalbG" failed: Operation not permitted (1)
rsync: mkstemp "/data/tmp/js/.README.md.jCIKNJ" failed: Operation not permitted (1)
rsync: mkstemp "/data/tmp/js/.index.php.hdDMkl" failed: Operation not permitted (1)
rsync: mkstemp "/data/tmp/js/.piwik.js.jCnmKo" failed: Operation not permitted (1)
rsync: mkstemp "/data/tmp/js/.piwik.min.js.JpjdoJ" failed: Operation not permitted (1)
rsync: mkstemp "/data/tmp/js/.tracker.php.iMeeEC" failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
```
