### ISSUE TITLE
Matomo 4.6.0 is out

### ISSUE THREAD

**Issue by Nuklon** [crazy-max/docker-matomo#84]
With an important security update.

Perhaps we can add a bot to this repo to automatically update Matomo?

**Comment by rafaelmaeuer** [comment]
just wanted to add a note as the PR-link popped in, thanks - great job guys :)

**Comment by rafaelmaeuer** [comment]
As the Matomo 4.6.0 update causes integrity check error: https://github.com/matomo-org/matomo/issues/18412 upgrading to v4.6.1 might be worth it?

![image](https://user-images.githubusercontent.com/6418459/144150602-8c9c3ac2-2206-4a4f-9deb-34dfa5676a0b.png)

Removing the file results in another error message complaining the file is now missing ¯\_(ツ)_/¯
