### ISSUE TITLE
What is the username/password for matomo admin?

### ISSUE THREAD

**Issue by linxiaolicnic** [crazy-max/docker-matomo#87]
#### Steps to reproduce this issue

1.What is the username/password for matomo admin?
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

* Docker version (type `docker --version`) :
* Docker compose version if applicable (type `docker-compose --version`) : 
* Platform (Debian 9, Ubuntu 18.04, ...) : 
* System info (type `uname -a`) : 
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

**Comment by crazy-max** [comment]
@linxiaolicnic There is no defaults. You have to use the wizard the first time you run this container.
